---
abstract: 'Read and write GNU gettext po/mo files'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  File::DataClass: v0.20.0
  Module::Build: 0.4004
  Text::Diff: 1.37
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Gettext
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  File::Gettext:
    file: lib/File/Gettext.pm
    version: v0.17.1
  File::Gettext::Constants:
    file: lib/File/Gettext/Constants.pm
    version: v0.17.1
  File::Gettext::ResultSource:
    file: lib/File/Gettext/ResultSource.pm
    version: v0.17.1
  File::Gettext::Schema:
    file: lib/File/Gettext/Schema.pm
    version: v0.17.1
  File::Gettext::Storage:
    file: lib/File/Gettext/Storage.pm
    version: v0.17.1
  File::Gettext::Storage::MO:
    file: lib/File/Gettext/Storage/MO.pm
    version: v0.17.1
  File::Gettext::Storage::PO:
    file: lib/File/Gettext/Storage/PO.pm
    version: v0.17.1
recommends:
  App::cpanminus: 1.6005
requires:
  Date::Format: 2.22
  Encode: 2.12
  File::DataClass: v0.20.0
  Moose: 2.0801
  MooseX::Types: 0.35
  Sub::Exporter::Progressive: 0.001006
  Try::Tiny: 0.09
  namespace::autoclean: 0.13
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Gettext
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.17.1
