---
abstract: 'Read and write GNU gettext po/mo files'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  Test::Requires: 0.06
  Text::Diff: 1.37
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Gettext
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  File::Gettext:
    file: lib/File/Gettext.pm
    version: v0.22.1
  File::Gettext::Constants:
    file: lib/File/Gettext/Constants.pm
    version: v0.22.1
  File::Gettext::ResultSource:
    file: lib/File/Gettext/ResultSource.pm
    version: v0.22.1
  File::Gettext::Schema:
    file: lib/File/Gettext/Schema.pm
    version: v0.22.1
  File::Gettext::Storage:
    file: lib/File/Gettext/Storage.pm
    version: v0.22.1
  File::Gettext::Storage::MO:
    file: lib/File/Gettext/Storage/MO.pm
    version: v0.22.1
  File::Gettext::Storage::PO:
    file: lib/File/Gettext/Storage/PO.pm
    version: v0.22.1
requires:
  Class::Method::ModifiersX::Augment: 0.001
  Date::Format: 2.22
  Encode: 2.12
  File::DataClass: v0.28.0
  Moo: 1.003001
  Try::Tiny: 0.18
  Type::Tiny: 0.012
  Unexpected: v0.20.0
  namespace::sweep: 0.006
  perl: 5.010001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Gettext
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.22.1
