---
abstract: 'Read and write GNU gettext po/mo files'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: '0.4004'
  Test::Requires: '0.06'
  Text::Diff: '1.37'
  version: '0.88'
configure_requires:
  Module::Build: '0.4004'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Gettext
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  File::Gettext:
    file: lib/File/Gettext.pm
    version: v0.25.1
  File::Gettext::Constants:
    file: lib/File/Gettext/Constants.pm
    version: v0.25.1
  File::Gettext::ResultSource:
    file: lib/File/Gettext/ResultSource.pm
    version: v0.25.1
  File::Gettext::Schema:
    file: lib/File/Gettext/Schema.pm
    version: v0.25.1
  File::Gettext::Storage:
    file: lib/File/Gettext/Storage.pm
    version: v0.25.1
  File::Gettext::Storage::MO:
    file: lib/File/Gettext/Storage/MO.pm
    version: v0.25.1
  File::Gettext::Storage::PO:
    file: lib/File/Gettext/Storage/PO.pm
    version: v0.25.1
requires:
  Class::Method::ModifiersX::Augment: '0.001'
  Date::Format: '2.22'
  Encode: '2.12'
  File::DataClass: v0.46.0
  Moo: '1.006000'
  Try::Tiny: '0.22'
  Type::Tiny: '1.000002'
  Unexpected: v0.30.0
  namespace::autoclean: '0.19'
  perl: '5.010001'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Gettext
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
  repository: git://github.com/pjfl/p5-file-gettext.git
version: 0.25.1
